### ISSUE TITLE
edac service status

### ISSUE THREAD

**Issue by treydock** [treydock/puppet-edac#5]
The edac service status in latest EL6 and EL7 is always exiting with return code 3.  The current method of defining the status as `edac-ctl --status --quiet` doesn't really work either.

**Comment by razorsedge** [comment]
This is impacting me as well.

**Comment by razorsedge** [comment]
@treydock The latest git HEAD works for me.  Can you push a new release to the Forge?

**Comment by treydock** [comment]
@razorsedge 1.0.0 has been released to forge.
